import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import ConditionalAppShell from "@/components/ConditionalAppShell";
import AIPalette from "@/components/AIPalette";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem("settings_theme");if(t==="light"||t==="dark")document.documentElement.setAttribute("data-theme",t);})();`,
          }}
        />
        <ConditionalAppShell>
          <Suspense fallback={<div style={{ padding: 24, minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--muted)" }}>読み込み中…</div>}>
            {children}
          </Suspense>
        </ConditionalAppShell>
        <AIPalette />
      </body>
    </html>
  );
}
